"""add snapshot_id to drift_records

Revision ID: 16e8a2f28b8d
Revises: 6489edd1408e
Create Date: 2025-12-27 11:08:44.418202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16e8a2f28b8d'
down_revision: Union[str, Sequence[str], None] = '6489edd1408e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drift_records', sa.Column('snapshot_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'drift_records', 'state_snapshots', ['snapshot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drift_records', type_='foreignkey')
    op.drop_column('drift_records', 'snapshot_id')
    # ### end Alembic commands ###
