"""add drift explanation

Revision ID: 19fae5b781b6
Revises: 1c00a1bfd724
Create Date: 2025-12-27 14:27:11.821418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19fae5b781b6'
down_revision: Union[str, Sequence[str], None] = '1c00a1bfd724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drift_records', sa.Column('explanation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drift_records', 'explanation')
    # ### end Alembic commands ###
